# Generated by Django 3.2.16 on 2026-01-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('is_published', models.BooleanField(default=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post_in_Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('is_published', models.BooleanField(default=True)),
                ('info', models.TextField()),
            ],
        ),
    ]
