# Generated by Django 5.1.1 on 2026-03-28 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('is_published', models.BooleanField(default=True)),
                ('info', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Заголовок:')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать:')),
                ('date_post', models.DateTimeField(verbose_name='Дата публикации:')),
                ('description', models.TextField(verbose_name='Детально о идеи:')),
                ('realisation', models.BooleanField(default=False, help_text='Когда ваша идея будет реализована, поставьте галочку)', verbose_name='Реализация:')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
        ),
        migrations.CreateModel(
            name='Post_in_Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название поста:')),
                ('is_published', models.BooleanField(default=True)),
                ('info', models.TextField(verbose_name='Основная информация о посте:')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Дата публикации:')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_about_Python.category', verbose_name='Категория поста:')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=34, verbose_name='Текст комментария')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_about_Python.post_in_python', verbose_name='Пост')),
            ],
        ),
    ]
