# Generated by Django 5.1.1 on 2026-03-28 18:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model_Form',
            new_name='Idea',
        ),
    ]
