# Generated by Django 3.2.16 on 2026-01-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_in_python',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_about_Python.category'),
        ),
    ]
