# Generated by Django 3.2.16 on 2026-01-17 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0002_post_in_python_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_in_python',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
