# Generated by Django 3.2.16 on 2026-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0003_post_in_python_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=list, unique=True),
            preserve_default=False,
        ),
    ]
