# Generated by Django 3.2.16 on 2026-01-18 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0004_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='the_history_of_python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('is_published', models.BooleanField(default=True)),
                ('info', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='post_in_python',
            name='the_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_about_Python.the_history_of_python'),
        ),
    ]
