# Generated by Django 3.2.16 on 2026-01-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0005_auto_20260119_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True)),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='post_in_python',
            name='the_history',
        ),
        migrations.DeleteModel(
            name='the_history_of_python',
        ),
    ]
