# Generated by Django 3.2.16 on 2026-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0006_auto_20260120_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_form',
            name='realisation',
            field=models.BooleanField(default=False, help_text='Кода ваша идея будет реализована, поставьте галочку'),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='description',
            field=models.TextField(verbose_name='Детально о идеи:'),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Ваш user_name:'),
        ),
    ]
