# Generated by Django 3.2.16 on 2026-01-27 10:03

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0007_auto_20260124_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_form',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 27, 10, 3, 45, 896962, tzinfo=utc), verbose_name='Дата публикации:'),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать:'),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='realisation',
            field=models.BooleanField(default=False, help_text='Когда ваша идея будет реализована, поставьте галочку)', verbose_name='Реализация:'),
        ),
        migrations.AlterField(
            model_name='post_in_python',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_about_Python.category', verbose_name='Категория поста:'),
        ),
        migrations.AlterField(
            model_name='post_in_python',
            name='info',
            field=models.TextField(verbose_name='Основная информация о посте:'),
        ),
        migrations.AlterField(
            model_name='post_in_python',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации:'),
        ),
        migrations.AlterField(
            model_name='post_in_python',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название поста:'),
        ),
    ]
