# Generated by Django 3.2.16 on 2026-01-28 13:19

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0009_auto_20260127_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='all_about_Python.post_in_python', verbose_name='Пост')),
            ],
        ),
        migrations.AlterField(
            model_name='model_form',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 13, 19, 18, 259113, tzinfo=utc), verbose_name='Дата публикации:'),
        ),
        migrations.DeleteModel(
            name='Comment_Post',
        ),
    ]
