# Generated by Django 3.2.16 on 2026-01-28 13:29

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0010_auto_20260128_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_model',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='all_about_Python.post_in_python', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 13, 29, 41, 455601, tzinfo=utc), verbose_name='Дата публикации:'),
        ),
    ]
