# Generated by Django 3.2.16 on 2026-01-30 12:11

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_about_Python', '0011_auto_20260128_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_model',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AddField(
            model_name='model_form',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AddField(
            model_name='post_in_python',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=123),
        ),
        migrations.AlterField(
            model_name='comment_model',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_about_Python.post_in_python', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='comment_model',
            name='text',
            field=models.CharField(max_length=34, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 30, 12, 11, 1, 54419, tzinfo=utc), verbose_name='Дата публикации:'),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Ваш user_name:'),
        ),
        migrations.AlterField(
            model_name='post_in_python',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название поста:'),
        ),
    ]
