# Generated by Django 3.2.16 on 2026-03-14 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_Python', '0012_auto_20260130_1711'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='model_form',
            name='Unique person constraint',
        ),
        migrations.AlterField(
            model_name='model_form',
            name='date_post',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации:'),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Заголовок:'),
        ),
        migrations.AlterField(
            model_name='post_in_python',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации:'),
        ),
    ]
