# Generated by Django 3.2.16 on 2026-03-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInterviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('problem_solving', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TheoryOfTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic_Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=15)),
                ('practical_tasks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.taskinterviews')),
                ('theory_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.theoryoftopic')),
            ],
        ),
    ]
