# Generated by Django 5.1.1 on 2026-03-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_groupsuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsuser',
            name='messages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.message'),
            preserve_default=False,
        ),
    ]
