# Generated by Django 5.1.1 on 2026-03-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_groupsuser_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsuser',
            name='messages',
        ),
    ]
