# Generated by Django 5.1.1 on 2026-03-25 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_groupsuser_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsuser',
            name='participant',
        ),
        migrations.AddField(
            model_name='groupsuser',
            name='participant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
