# Generated by Django 5.1.1 on 2026-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_groupsuser_participant_groupsuser_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_anonumos',
            field=models.BooleanField(default=False),
        ),
    ]
