# Generated by Django 5.1.1 on 2026-03-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_message_is_anonumos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_anonumos',
            new_name='is_anonymous',
        ),
    ]
